# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6bc08d6a25d4d9395aa0bcf6d4c617a"
name = "Countdown Timer Bar"
handle = "countdown-timer-bar-5"
application_url = "https://rendan.website/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://darrenbe.website/shopify/finalize",
  "https://rendan.website/"
]

[pos]
embedded = false
